server:
  servlet:
    encoding:
      charset : UTF-8
      force-response: true
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password:
#
#  mustache:
#    expose-request-attributes: true
#
#jwt:
#  token:
#    secret: "secretKey"

